[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.1"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NEXT_PUBLIC_APP_URL = "https://syndicate-lens.netlify.app"
  NEXT_PUBLIC_ENVIRONMENT = "mainnet"
  NEXT_PUBLIC_LENS_MAINNET_RPC_URL = "https://rpc.lens.xyz"
  NEXT_PUBLIC_LENS_TESTNET_RPC_URL = "https://rpc.testnet.lens.xyz"
  NEXT_PUBLIC_BASE_CHAIN_RPC_URL = "https://mainnet.base.org"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]} 